### ISSUE TITLE
Cannot access 'NestedIntFilter' before initialization

### ISSUE THREAD

**Issue by murunwas** [mk668a/nestjs-prisma-graphql-crud-gen#28] opened 2022-08-06 09:38 UTC
I followed all the step showed on README, but when I run the application, I'm getting this error

/workspaces/nest-demo/src/generated/common/inputs.ts:28
  not?: NestedIntFilter | undefined;
        ^
ReferenceError: Cannot access 'NestedIntFilter' before initialization
    at Object.<anonymous> (/workspaces/nest-demo/src/generated/common/inputs.ts:28:9)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/workspaces/nest-demo/src/generated/article/inputs/ArticleScalarWhereWithAggregatesInput.input.ts:2:1)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)

**Comment by mk668a** [comment] 2022-08-06 11:01
Thanks!
The cause is that NestedIntFilter is used before the declaration.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Cant_access_lexical_declaration_before_init

I will fix that immediately.
You can now address this by moving the location of the NestedIntFilter declaration.

**Comment by mk668a** [comment] 2022-08-06 12:09
Done in [223cbcc](https://github.com/mk668a/nestjs-prisma-graphql-crud-gen/pull/29/files), released in [v1.0.3](https://github.com/mk668a/nestjs-prisma-graphql-crud-gen/releases/tag/v1.0.3)

**Closed** 2022-08-06 12:09 UTC
